In [2]:
class Employee:
    # data member to count the number of Employees
    no_of_employees = 0

    def __init__(my, name, family_name, salary, department):
        my.__name = name
        my.__family_name = family_name
        my.salary = salary
        my.__department = department
        Employee.no_of_employees += 1
    @staticmethod
    def average_salary(employees):#function to average salary
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees
class FulltimeEmployee(Employee): 
    """
    
    """

    def __init__(my, name, family_name, salary, department):
        super().__init__(my, family_name, salary, department)

    def full_time_benefits(my):
        print("Few benefits as full time employee.")


def main():
    employees = []
    fte1 = FulltimeEmployee("shruthi", "Vallap Reddy", 5000000, "Principal")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("Suvidha", "Manda", 20000, "Vice Principal")
    employees.append(fte2)
    emp1 = Employee("Ruchitha", "Babburi", 200, "Peon")
    employees.append(emp1)
    emp2 = Employee("Sindhu", "Maryadha", 10000, "Professor")
    employees.append(emp2)
    print("Average salary of all employees :", FulltimeEmployee.average_salary(employees))
    print("No of Employees",Employee.no_of_employees)


if __name__ == "__main__":
    main()

Few benefits as full time employee.
Average salary of all employees : 1257550.0
No of Employees 4


In [35]:
import numpy as np

# Generate a random vector of size 20 with float numbers between 1 and 20
random_vector = np.random.uniform(1,20,(4,5))
print("vector before reshape",random_vector)

# Reshape the vector to  4 by 5
max_index = random_vector.reshape(5,4)
print("vector after reshape",max_index)

# Replace the maximum value in each row with 0
max_index[np.arange(5), max_index.argmax(axis=1)] = 0

print("replaced maximum value in each row with 0",max_index)

vector before reshape [[14.30622329 14.56278983  3.24618323 10.95782106  5.29252048]
 [14.32370996 10.21424029 10.94965577 13.18038448  1.8342874 ]
 [ 6.6942082   4.53055474  4.51416789  9.92225887 15.31969573]
 [18.39372588 14.59072553 17.23559422 18.36180044  7.07314153]]
vector after reshape [[14.30622329 14.56278983  3.24618323 10.95782106]
 [ 5.29252048 14.32370996 10.21424029 10.94965577]
 [13.18038448  1.8342874   6.6942082   4.53055474]
 [ 4.51416789  9.92225887 15.31969573 18.39372588]
 [14.59072553 17.23559422 18.36180044  7.07314153]]
replaced maximum value in each row with 0 [[14.30622329  0.          3.24618323 10.95782106]
 [ 5.29252048  0.         10.21424029 10.94965577]
 [ 0.          1.8342874   6.6942082   4.53055474]
 [ 4.51416789  9.92225887 15.31969573  0.        ]
 [14.59072553 17.23559422  0.          7.07314153]]
